name: iAUTO - Motor de Inteligência

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  varredura:
    runs-on: ubuntu-latest
    steps:
      - name: Acionando Varredura de Fontes
        run: |
          curl -L "https://script.google.com/macros/s/AKfycby1us82agmsf40yWXO_zf3_Jlj5w17oTuuacf4_LkSKqBHzGOl0g2XEoA27KnFfWwB9/exec?action=executarVarreduraMassa"
