name: iAUTO - Motor de Inteligência

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  varredura:
    runs-on: ubuntu-latest
    steps:
      - name: Acionando Varredura
        run: |
          curl -L "https://script.google.com/macros/s/AKfycbyUmHUolu-Ha91ajepboHzGyjnAYnpDfrQvXH-N15uRWJZCGBAY8iVDkbqH8WR9saNl/exec"
